Include org.ietf.jgss in "Import-Package" list.
Resolve java.lang.NoClassDefFoundErrors related to missing org.ietf.jgss
classes in an OSGi container by including the package (optionally) in the
"Import-Package" list.